version: '2'

services:
  backend:
    build:
      context: ''
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
  frontend:
    build:
      context: './client'
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    
